### PR TITLE
Ap 2216/validate container command

### PR DESCRIPTION
**Pull request by rsandmann**
This PR adds validation of the container command to the `submit_aws_batch_job` lambda.

It does so by parsing CLI options that are accepted by MetaFlow and raises an exception if any unknown options are encountered in the command. This is rather restrictive, so doesn't allow for much flexibility which is what we might want in this case.

The disadvantage is that with an update of MetaFlow (which is unlikely in the near future because that would mean we'd have to adjust our custom MetaFlow code), we would also need to update the lambda in the nodes.

### CODE REVIEW

**Comment by cmertzaph** [comment]
Shall we test it tomorrow?

**Comment by rsandmann** [comment]
That would be great! :)

**Comment by cmertzaph** [comment]
As mentioned in the call we had to test it:

Kind of an odd request but i'd remove most of the comments in the function, given that they end up in the template that we hand out and we probably do not want to draw too much attention to how we do things in the lambda (the fact that we use a heuristic for this).

**Review by cmertzaph — APPROVED** [review]
LGTM

**Review by c-hartig — APPROVED** [review]

**Pull request merged**
